services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/db:/app/db  # Monte uniquement le répertoire db
    networks:
      - epsi_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./frontend/static:/usr/share/nginx/html:ro  # Monte uniquement le dossier static
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - epsi_network

networks:
  epsi_network:
    driver: bridge